"""Seed data for Baume e-commerce (French feminine wellness)."""

# Image library: Unsplash / Pexels URLs aligned with soft, premium, feminine wellness aesthetic.
IMG = {
    "lingerie_1": "https://images.unsplash.com/photo-1595777216528-071e0127ccbf?auto=format&fit=crop&w=1200&q=80",
    "lingerie_2": "https://images.unsplash.com/photo-1617051397070-d54b7ee00f2a?auto=format&fit=crop&w=1200&q=80",
    "swim": "https://images.unsplash.com/photo-1570976447640-ac859083963c?auto=format&fit=crop&w=1200&q=80",
    "cup": "https://images.unsplash.com/photo-1628602435593-24ea8c4541f2?auto=format&fit=crop&w=1200&q=80",
    "pad": "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=1200&q=80",
    "soin_1": "https://images.unsplash.com/photo-1556228578-dd6f8f3f8f0b?auto=format&fit=crop&w=1200&q=80",
    "soin_2": "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=1200&q=80",
    "soin_3": "https://images.unsplash.com/photo-1611930021592-a3f8b6f0f5c0?auto=format&fit=crop&w=1200&q=80",
    "lub": "https://images.unsplash.com/photo-1617897903246-719242758050?auto=format&fit=crop&w=1200&q=80",
    "complement": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=1200&q=80",
    "accessoire": "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1200&q=80",
    "pouch": "https://images.unsplash.com/photo-1627914931089-25b6e4f90a98?auto=format&fit=crop&w=1200&q=80",
    "botanical": "https://images.unsplash.com/photo-1607006677668-33fcc29add7a?auto=format&fit=crop&w=1200&q=80",
    "wellness": "https://images.pexels.com/photos/7365410/pexels-photo-7365410.jpeg?auto=compress&cs=tinysrgb&w=1200",
    "boutique": "https://images.unsplash.com/photo-1604176354204-9268737828e4?auto=format&fit=crop&w=1600&q=80",
    "hero": "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1600&q=80",
    "portrait_1": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=800&q=80",
    "portrait_2": "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=800&q=80",
    "portrait_3": "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=800&q=80",
    "editorial_1": "https://images.unsplash.com/photo-1526413232644-8a40f03cc03b?auto=format&fit=crop&w=1200&q=80",
    "editorial_2": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
    "editorial_3": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80",
}


NEEDS = [
    {"slug": "regles-cycle", "name": "Règles & cycle", "tagline": "Vivre son cycle en confiance.",
     "description": "Protections menstruelles douces, absorbantes et sûres pour chaque jour du cycle.",
     "image": IMG["lingerie_1"]},
    {"slug": "intimite", "name": "Intimité", "tagline": "Prendre soin de sa flore au quotidien.",
     "description": "Soins lavants, hydratants et rééquilibrants, sélectionnés pour la zone intime.",
     "image": IMG["soin_1"]},
    {"slug": "sexualite", "name": "Sexualité", "tagline": "Plaisir, sensualité, connaissance de soi.",
     "description": "Lubrifiants, accessoires et rituels pour une sexualité libre et informée.",
     "image": IMG["lub"]},
    {"slug": "maternite-post-partum", "name": "Maternité & post-partum",
     "tagline": "Accompagner les mois qui changent tout.",
     "description": "Produits pensés pour la grossesse, l'après-naissance et les premières semaines.",
     "image": IMG["editorial_2"]},
    {"slug": "peri-menopause", "name": "Péri-ménopause", "tagline": "Traverser cette étape en douceur.",
     "description": "Soins et compléments adaptés aux variations hormonales et au confort intime.",
     "image": IMG["editorial_1"]},
    {"slug": "ados", "name": "Ados & premiers cycles", "tagline": "Bien commencer, sans pression.",
     "description": "Protections simples et ressources pour accompagner les premiers cycles.",
     "image": IMG["editorial_3"]},
]

PRODUCT_CATEGORIES = [
    {"slug": "culottes-menstruelles", "name": "Culottes menstruelles",
     "tagline": "Confort absolu, absorption maîtrisée.", "description": "Une alternative réutilisable, douce et fiable.",
     "image": IMG["lingerie_1"]},
    {"slug": "maillots-menstruels", "name": "Maillots menstruels",
     "tagline": "Se baigner sereinement, même pendant ses règles.",
     "description": "Maillots techniques qui permettent la baignade en toute liberté.",
     "image": IMG["swim"]},
    {"slug": "cups-disques", "name": "Cups & disques",
     "tagline": "Une protection interne réutilisable et durable.",
     "description": "Cups en silicone médical et disques souples, pour chaque morphologie.",
     "image": IMG["cup"]},
    {"slug": "serviettes-lavables", "name": "Serviettes lavables",
     "tagline": "Douces pour la peau, zéro déchet.",
     "description": "Serviettes en coton certifié, lavables et longue durée.",
     "image": IMG["pad"]},
    {"slug": "soins-intimes", "name": "Soins intimes",
     "tagline": "Hygiène et confort, pensés pour la zone intime.",
     "description": "Nettoyants doux, huiles apaisantes, soins rééquilibrants.",
     "image": IMG["soin_2"]},
    {"slug": "lubrifiants", "name": "Lubrifiants",
     "tagline": "Glissance naturelle, formules clean.",
     "description": "Lubrifiants à base d'eau ou de silicone, sans parfum ni parabens.",
     "image": IMG["lub"]},
    {"slug": "complements", "name": "Compléments",
     "tagline": "Soutenir le cycle, l'équilibre hormonal et la vitalité.",
     "description": "Compléments alimentaires naturels et ciblés.",
     "image": IMG["complement"]},
    {"slug": "accessoires-cadeaux", "name": "Accessoires & cadeaux",
     "tagline": "Rituels, coffrets et petites attentions.",
     "description": "Pochettes, bouillottes, coffrets cadeaux pensés avec soin.",
     "image": IMG["accessoire"]},
]


def _p(pid, slug, name, tagline, price, img, cat, needs, **kwargs):
    return {
        "id": pid, "slug": slug, "name": name, "tagline": tagline, "price": price,
        "image": img, "gallery": kwargs.get("gallery", [img, IMG["botanical"], IMG["editorial_1"]]),
        "product_category": cat, "needs": needs,
        "flux": kwargs.get("flux"), "usage": kwargs.get("usage"),
        "sizes": kwargs.get("sizes", []), "colors": kwargs.get("colors", []),
        "benefits": kwargs.get("benefits", []),
        "description": kwargs.get("description", tagline),
        "composition": kwargs.get("composition", "Matières certifiées, traçables, respectueuses de la peau."),
        "how_to_use": kwargs.get("how_to_use", "Suivre les indications sur l'emballage."),
        "fabrication": kwargs.get("fabrication", "Fabrication européenne, conditions éthiques."),
        "rating": kwargs.get("rating", 4.8),
        "reviews_count": kwargs.get("reviews_count", 42),
        "stock": kwargs.get("stock", 50),
        "available": kwargs.get("available", True),
        "bestseller": kwargs.get("bestseller", False),
        "featured": kwargs.get("featured", False),
        "currency": "CHF",
        "compare_price": kwargs.get("compare_price"),
    }


PRODUCTS = [
    _p("p1", "culotte-confort-nuit", "Culotte Confort Nuit", "Absorption nuit, coton bio, coupe haute.",
       42.0, IMG["lingerie_1"], "culottes-menstruelles", ["regles-cycle"],
       flux="abondant", usage="nuit", sizes=["XS", "S", "M", "L", "XL"], colors=["Noir", "Bordeaux"],
       benefits=["Absorption 4 tampons", "Coton bio certifié", "Zéro fuite", "Lavable 150 cycles", "Séchage rapide"],
       bestseller=True, featured=True, reviews_count=218, rating=4.9),
    _p("p2", "culotte-jour-taille-basse", "Culotte Jour Taille Basse", "Discrétion et absorption moyenne.",
       36.0, IMG["lingerie_2"], "culottes-menstruelles", ["regles-cycle", "ados"],
       flux="moyen", usage="jour", sizes=["XS", "S", "M", "L"], colors=["Noir", "Ivoire"],
       benefits=["Absorption 2-3 tampons", "Dentelle douce", "Coupe invisible", "Respirant"],
       bestseller=True, reviews_count=142),
    _p("p3", "culotte-sport", "Culotte Sport", "Tenue active, absorption sûre.",
       39.0, IMG["lingerie_1"], "culottes-menstruelles", ["regles-cycle"],
       flux="moyen", usage="sport", sizes=["S", "M", "L"], colors=["Noir"],
       benefits=["Maintien renforcé", "Thermorégulant", "Séchage rapide"]),
    _p("p4", "maillot-une-piece", "Maillot Une Pièce", "Baignade sereine pendant les règles.",
       89.0, IMG["swim"], "maillots-menstruels", ["regles-cycle"],
       flux="leger", usage="jour", sizes=["XS", "S", "M", "L", "XL"], colors=["Noir", "Bourgogne"],
       benefits=["Absorption 2 tampons", "Séchage rapide", "Résistant au chlore", "UPF 50+"],
       bestseller=True, featured=True, reviews_count=96, rating=4.8),
    _p("p5", "maillot-deux-pieces", "Bas de Maillot", "Bas menstruel à associer.",
       59.0, IMG["swim"], "maillots-menstruels", ["regles-cycle"],
       flux="leger", sizes=["XS", "S", "M", "L"], colors=["Noir"],
       benefits=["Invisible", "Résistant au sel", "Séchage rapide"]),
    _p("p6", "cup-taille-1", "Cup Silicone Taille 1", "Silicone médical, flux léger à moyen.",
       28.0, IMG["cup"], "cups-disques", ["regles-cycle", "ados"],
       flux="moyen", sizes=["Taille 1"], colors=["Transparent"],
       benefits=["Silicone médical", "Jusqu'à 8h", "Réutilisable 10 ans", "Sans BPA"],
       bestseller=True, reviews_count=312, rating=4.7),
    _p("p7", "cup-taille-2", "Cup Silicone Taille 2", "Flux moyen à abondant.",
       28.0, IMG["cup"], "cups-disques", ["regles-cycle", "maternite-post-partum"],
       flux="abondant", sizes=["Taille 2"], colors=["Transparent", "Rose"],
       benefits=["Silicone médical", "Jusqu'à 12h", "Large capacité", "Hypoallergénique"],
       reviews_count=187),
    _p("p8", "disque-menstruel", "Disque Menstruel", "Confort ultra-fin, zero sensation.",
       32.0, IMG["cup"], "cups-disques", ["regles-cycle", "sexualite"],
       flux="abondant", sizes=["Unique"], colors=["Transparent"],
       benefits=["Confort invisible", "Compatible intimité", "Jusqu'à 12h"]),
    _p("p9", "serviettes-lavables-jour", "Serviettes Lavables Jour (x3)", "Coton bio certifié, douces.",
       34.0, IMG["pad"], "serviettes-lavables", ["regles-cycle", "ados"],
       flux="moyen", usage="jour", sizes=["Jour"], colors=["Ivoire", "Bordeaux"],
       benefits=["Coton bio GOTS", "3 épaisseurs", "Attache pression", "Lavable 100+ fois"],
       reviews_count=78),
    _p("p10", "serviettes-lavables-nuit", "Serviettes Lavables Nuit (x2)", "Absorption longue.",
       32.0, IMG["pad"], "serviettes-lavables", ["regles-cycle"],
       flux="abondant", usage="nuit", sizes=["Nuit"], colors=["Noir"],
       benefits=["Haute absorption", "Coton bio", "Confort nuit"]),
    _p("p11", "nettoyant-intime-doux", "Nettoyant Intime Doux", "pH physiologique, sans parfum.",
       18.0, IMG["soin_1"], "soins-intimes", ["intimite", "maternite-post-partum", "peri-menopause"],
       sizes=["200ml"],
       benefits=["pH 5.2", "Sans parfum ni savon", "Prébiotiques", "Testé gynéco"],
       featured=True, reviews_count=256, rating=4.9),
    _p("p12", "huile-intime-apaisante", "Huile Intime Apaisante", "Calendula, amande, ricin.",
       26.0, IMG["soin_2"], "soins-intimes", ["intimite", "peri-menopause"],
       sizes=["50ml"],
       benefits=["Formule naturelle", "Apaise les tiraillements", "Non gras"],
       bestseller=True, reviews_count=164),
    _p("p13", "creme-hydratante-intime", "Crème Hydratante Intime", "Confort quotidien.",
       28.0, IMG["soin_3"], "soins-intimes", ["intimite", "peri-menopause"],
       sizes=["75ml"],
       benefits=["Hydratation longue durée", "Sans hormone", "Formule clean"]),
    _p("p14", "lubrifiant-eau", "Lubrifiant à base d'eau", "Glissance naturelle, formule clean.",
       22.0, IMG["lub"], "lubrifiants", ["sexualite", "peri-menopause", "maternite-post-partum"],
       sizes=["100ml"],
       benefits=["Compatible préservatif", "Sans parfum", "Sans parabens", "Vegan"],
       bestseller=True, reviews_count=198, rating=4.8),
    _p("p15", "lubrifiant-silicone", "Lubrifiant Silicone", "Longue tenue, sensation veloutée.",
       28.0, IMG["lub"], "lubrifiants", ["sexualite"],
       sizes=["50ml"],
       benefits=["Très longue tenue", "Résistant à l'eau", "Ultra doux"]),
    _p("p16", "complement-cycle", "Complément Cycle Équilibré", "Plantes adaptogènes, cure 30 jours.",
       34.0, IMG["complement"], "complements", ["regles-cycle", "peri-menopause"],
       sizes=["60 gélules"],
       benefits=["Vitex, gattilier, magnésium", "Origine France", "Vegan"],
       reviews_count=87),
    _p("p17", "complement-maternite", "Complément Post-Partum", "Soutien des premiers mois.",
       38.0, IMG["complement"], "complements", ["maternite-post-partum"],
       sizes=["60 gélules"],
       benefits=["Fer, zinc, oméga 3", "Compatible allaitement", "Testé clinique"]),
    _p("p18", "bouillotte-graines", "Bouillotte Graines", "Chaleur douce, coton bio.",
       42.0, IMG["pouch"], "accessoires-cadeaux", ["regles-cycle", "intimite"],
       colors=["Ivoire", "Bordeaux"],
       benefits=["Chaleur 30 min", "Graines de lin", "Lavable"],
       reviews_count=64),
    _p("p19", "pochette-culotte", "Pochette de transport", "Coton lavable, discrète.",
       16.0, IMG["pouch"], "accessoires-cadeaux", ["regles-cycle"],
       colors=["Ivoire", "Noir"],
       benefits=["Imperméable", "Lavable", "Zipper doux"]),
    _p("p20", "coffret-decouverte", "Coffret Découverte", "Le rituel Baume à offrir.",
       89.0, IMG["accessoire"], "accessoires-cadeaux", ["intimite", "regles-cycle"],
       benefits=["3 essentiels", "Emballage cadeau", "Livret d'accompagnement"],
       featured=True, bestseller=True, reviews_count=54, rating=4.9,
       compare_price=108.0),
]


REVIEWS = [
    {"id": "r1", "author": "Claire M.", "product_id": "p1", "rating": 5,
     "title": "Enfin une nuit sereine", "content": "J'ai testé 3 marques, la Baume est de loin la plus confortable. Zéro fuite, tissu doux.",
     "date": "2025-11-12"},
    {"id": "r2", "author": "Inès R.", "product_id": "p6", "rating": 5,
     "title": "Adoptée pour la vie", "content": "La cup a transformé mon rapport aux règles. Accompagnement en boutique parfait.",
     "date": "2025-10-30"},
    {"id": "r3", "author": "Sophie B.", "product_id": "p11", "rating": 5,
     "title": "Irritations envolées", "content": "Ma gynéco m'avait conseillé un pH doux : ce nettoyant est parfait.",
     "date": "2025-11-02"},
    {"id": "r4", "author": "Léa T.", "product_id": "p14", "rating": 5,
     "title": "Formule clean, efficace", "content": "Aucun parfum, texture fluide. Exactement ce que je cherchais.",
     "date": "2025-10-18"},
    {"id": "r5", "author": "Marie D.", "product_id": "p4", "rating": 5,
     "title": "Vacances tranquilles", "content": "Enfin je peux me baigner pendant mes règles sans stress.",
     "date": "2025-08-22"},
    {"id": "r6", "author": "Nadia K.", "product_id": None, "rating": 5,
     "title": "Boutique magnifique", "content": "L'équipe de Genève est à l'écoute, prend le temps. On se sent accueillie.",
     "date": "2025-11-05"},
]


GUIDES = [
    {"slug": "choisir-sa-culotte-menstruelle", "title": "Comment choisir sa culotte menstruelle ?",
     "excerpt": "Flux, taille, coupe, matière : tout ce qu'il faut savoir avant d'acheter.",
     "image": IMG["editorial_1"], "category": "Règles & cycle", "read_time": "6 min",
     "content": "Une culotte menstruelle se choisit selon votre flux, votre morphologie et votre usage. Commencez par identifier votre journée la plus abondante, puis choisissez une absorption équivalente à 2-4 tampons. La coupe taille basse convient aux jeans, la coupe haute est idéale la nuit. Privilégiez des matières certifiées (OEKO-TEX, GOTS) et vérifiez la durabilité annoncée par la marque (150 cycles minimum pour Baume)."},
    {"slug": "premieres-regles-accompagner", "title": "Premières règles : accompagner en douceur",
     "excerpt": "Conseils pour parler, choisir les bonnes protections et vivre cette étape sans stress.",
     "image": IMG["editorial_2"], "category": "Ados", "read_time": "5 min",
     "content": "Accompagner une ado dans ses premiers cycles passe d'abord par l'écoute et la normalisation. Proposez plusieurs types de protections (culottes, serviettes lavables, tampons) pour qu'elle puisse choisir. Notre boutique Genève accueille les familles pour un moment pédagogique et bienveillant."},
    {"slug": "post-partum-premieres-semaines", "title": "Post-partum : les premières semaines",
     "excerpt": "Saignements, confort, cicatrisation : les essentiels du 4e trimestre.",
     "image": IMG["editorial_3"], "category": "Maternité", "read_time": "8 min",
     "content": "Les semaines post-accouchement demandent des protections ultra-absorbantes et des soins très doux. Nos culottes post-partum offrent une absorption maximale. Les huiles de soin à base de calendula apaisent les zones sensibles."},
    {"slug": "peri-menopause-inconfort-intime", "title": "Péri-ménopause : soulager l'inconfort intime",
     "excerpt": "Sécheresse, sensibilité : les solutions douces et efficaces.",
     "image": IMG["editorial_1"], "category": "Péri-ménopause", "read_time": "7 min",
     "content": "La péri-ménopause s'accompagne souvent de sécheresse intime. Les crèmes hydratantes sans hormones et les lubrifiants à base d'eau redonnent du confort au quotidien. Nos expertes genevoises reçoivent sur rendez-vous pour un bilan personnalisé."},
    {"slug": "cup-premier-usage", "title": "Cup : réussir sa première insertion",
     "excerpt": "Pliages, positions, astuces pour une prise en main sereine.",
     "image": IMG["editorial_2"], "category": "Règles & cycle", "read_time": "5 min",
     "content": "Respirez, détendez-vous, prenez votre temps. Pliez la cup en C ou en 7, insérez-la accroupie ou debout. Elle doit s'ouvrir complètement pour être étanche. Entraînez-vous quelques cycles avant de juger."},
    {"slug": "lubrifiant-bien-choisir", "title": "Lubrifiant : bien choisir sa formule",
     "excerpt": "Eau, silicone, hybride : quel lubrifiant pour quel usage ?",
     "image": IMG["editorial_3"], "category": "Sexualité", "read_time": "4 min",
     "content": "Les lubrifiants à base d'eau conviennent à tous les usages et sont compatibles avec les préservatifs. Les silicones offrent une tenue longue pour les moments prolongés ou dans l'eau. Évitez les parfums et glycérines."},
]


EXPERTS = [
    {"id": "e1", "name": "Camille Rousseau", "role": "Sage-femme, fondatrice Baume",
     "bio": "Camille accompagne les femmes à chaque étape depuis 15 ans. Consultations sur rendez-vous en boutique.",
     "image": IMG["portrait_1"], "specialties": ["Maternité", "Post-partum", "Cycle"]},
    {"id": "e2", "name": "Laura Benoit", "role": "Conseillère bien-être intime",
     "bio": "Laura reçoit en boutique pour des conseils personnalisés, choix de protection et soins.",
     "image": IMG["portrait_2"], "specialties": ["Cycle", "Intimité", "Ados"]},
    {"id": "e3", "name": "Dr. Sophie Meier", "role": "Gynécologue partenaire",
     "bio": "Ateliers mensuels sur la péri-ménopause, la sexualité et la santé intime.",
     "image": IMG["portrait_3"], "specialties": ["Péri-ménopause", "Sexualité"]},
]
